### ISSUE TITLE
timeseries/pyKEP

### ISSUE THREAD

**Issue by brunofisico** [IvS-KULeuven/IvSPythonRepository#15]
I'm having problems with the timeseries module. I tried to run directly inside /timeseries
**f2py --fcompiller=gfortran -c pyKEP.f -m pyKEP**
but to no avail. 
Within ipython the others are compiled.
What is wrong?

**Comment by mike-ivs** [comment]
Hi Bruno,

In the above command "compiler" seems to be misspelt, perhaps this is the problem?

If not, can you send the error message you recieve when attempting to compile?

**Comment by brunofisico** [comment]
If I put 'python config.py compile'
every taks are working...but the the messsage is:

(ivs_repo_3.6) bruno@Procyon:~/ivs$ python config.py compile
Sun, 20 Oct 2019 19:48 root INFO     PYROTIN4 already compiled
Sun, 20 Oct 2019 19:48 root INFO     DEEMING already compiled
Sun, 20 Oct 2019 19:48 root INFO     EEBLS already compiled
Sun, 20 Oct 2019 19:48 root INFO     MULTIH already compiled
Sun, 20 Oct 2019 19:48 root INFO     PYCLEAN already compiled
Sun, 20 Oct 2019 19:48 root INFO     Compiling PYKEP: f2py --fcompiler=gfortran -c timeseries/pyKEP.f -m pyKEP
rmbadname1: Replacing "index" with "index_bn".
Traceback (most recent call last):
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/bin/f2py", line 28, in <module>
    main()
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 683, in main
    run_compile()
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 650, in run_compile
    setup(ext_modules=[ext])
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 325, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
    ['-m', ext_name]+f_sources)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode
    dowithline(finalline)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline
    analyzeline(m, pat[1], line)
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline
    for e in markoutercomma(ll).split('@,@'):
  File "/home/bruno/.local/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'nmax=10000)  ! max. data point', 'nmax=10000)  ! max. data point')
Traceback (most recent call last):
  File "config.py", line 110, in <module>
    p = subprocess.check_output(cmd,shell=True)#,stdout=devnull)
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/bruno/anaconda3/envs/ivs_repo_3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'f2py --fcompiler=gfortran -c timeseries/pyKEP.f -m pyKEP' returned non-zero exit status 1.

**Comment by brunofisico** [comment]
I tried
cd timeseries
bruno@Procyon:~/ivs/timeseries$ f2py --fcompiler=gfortran -c pyKEP.f -m pyKEP
and the same error is show.

**Comment by mike-ivs** [comment]
Hmmm,

are you running it within ipython? If you are, could you try running it in a normal terminal/command line?

@karandis does this sound similar to your problem? I have no issues with the compilation, however for pyKEP i notice it does have to rename some variables when compiling, perhaps this becomes an issue when run in ipython?

**Comment by brunofisico** [comment]
Hi Mike. Thank you.
![erro](https://user-images.githubusercontent.com/20669797/67192295-b5779580-f3c9-11e9-9d0f-8c8f5dcb2c03.jpg)


In Really I tried install on terminal and this error was show.  If I use ipython, for me is clear, that task 'timeseries' has a problem. Take a look.

**Comment by karandis** [comment]
Hi Bruno, Mike,

I tried to reproduce this issue with a fresh installation of the repository, but it works fine for me. When running 'python config.py compile', I do get the warning with the variable that is renamed:

```
Tue, 22 Oct 2019 16:50 root INFO     Compiling PYKEP: f2py --fcompiler=gfortran -c timeseries/pyKEP.f -m pyKEP
rmbadname1: Replacing "index" with "index_bn".
analyzeline: Failed to evaluate '10000)  ! max. data point'. Ignoring: invalid syntax (<string>, line 1)
rmbadname1: Replacing "default" with "default_bn".
rmbadname1: Replacing "default" with "default_bn".
Tue, 22 Oct 2019 16:50 root INFO     ... succeeded

```
It still works, and I am able to load pyKEP in a terminal (from ivs.timeseries import pyKEP)
 

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>from ivs.timeseries import pyKEP
>>>
```

I would try reinstalling the repository and run config.py again.  I will look into what variable is renamed but in the meantime, please try it out and let us know!

Cheers,
Karan

**Comment by mike-ivs** [comment]
So I dug into this while on my train:

The pyKEP and pyGLS Fortran files were showing 'soft' syntax errors on our end when compiling, plus a few reserved variable namespace issues (such as "index", "max", "default", etc). Likely these are the 'hard' errors you have encountered with pyKEP (and maybe with pyGLS upon fresh install).

I've fixed the syntax errors by assigning the INTEGER,PARAMETERS properly in the Fortran files, and also changing the variable names. There don't appear to be any more compilation warnings/errors for now, and the test script in "time series/pergrams.py" seems to run everything properly.

I'll upload the fix tonight once I get off my train, and let you know when it's uploaded.

**Comment by brunofisico** [comment]
I will wait. Let me know any time if you need that I test for this. Karan, thank you too. I tried re-install but for now let wait the new task. the Best for all

**Comment by mike-ivs** [comment]
Just pushed the fixes up to master, if you can pull the latest repository version and try compiling the files that would be great (i have now added a recompile option to config.py to make life easier: "python config.py recompile"). I hope this fixes the compilation problems!

**Comment by brunofisico** [comment]
My friends, it works so easy...Thank all.
